server:
  port: 8082

spring:
  datasource:
    url: jdbc:tc:postgresql:16:///ias
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info,flyway,env,mappings
  endpoint:
    env:
      show-values: always

ias:
  jwt:
    issuer: dev-issuer
    secret:
      b64: ${IAS_JWT_SECRET_B64:VGhpcy1pcy1hLXRlc3QtZGV2LXNlY3JldC1iYXNlNjQ=}
    access-ttl-minutes: 15

logging:
  level:
    org.springframework.security: DEBUG
    com.kevdev.iam: DEBUG

