services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: iam
      POSTGRES_USER: iam
      POSTGRES_PASSWORD: iam
    ports:
      - "5433:5432"

  ias:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: local
      SECURITY_JWT_SECRET: dev_secret_dev_secret_dev_secret_dev_
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/iam
      SPRING_DATASOURCE_USERNAME: iam
      SPRING_DATASOURCE_PASSWORD: iam
    ports:
      - "8082:8082"
    depends_on:
      - db

