services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: iam
      POSTGRES_USER: iam
      POSTGRES_PASSWORD: iam
    ports:
      - "5433:5432"
    volumes:
      - iam_pgdata:/var/lib/postgresql/data

volumes:
  iam_pgdata:

